/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./app/**/*.{js,jsx,ts,tsx}", "./components/*.{js,jsx,ts,tsx}", "./screens/*.{js,jsx,ts,tsx}"],
  presets: [require("nativewind/preset")],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        // Surfaces — light stays a warm premium cream; dark deepened to a
        // near-black emerald for a richer "Emerald Luxe" feel.
        "bg-app": "#EFEDE4",
        "bg-app-dark": "#0A0F0C",
        "bg-card": "#FFFFFF",
        "bg-card-dark": "#121A14",
        "bg-subtle": "#ECEBE6",
        "bg-subtle-dark": "#18221A",
        "bg-close": "#F0EFE8",
        "bg-close-dark": "#16201A",
        // Text
        "tx-primary": "#16201A",
        "tx-primary-dark": "#E2E9E0",
        "tx-secondary": "#8E948C",
        "tx-secondary-dark": "#9EAE9C",
        "tx-tertiary": "#9AA096",
        "tx-tertiary-dark": "#7E8E7C",
        "tx-chip": "#6B7066",
        "tx-chip-dark": "#9AAA98",
        "tx-inactive": "#B4B9B0",
        "tx-inactive-dark": "#607060",
        // Borders
        "border-row": "#F3F2EB",
        "border-row-dark": "#252E23",
        "border-input": "#F0EFE8",
        "border-input-dark": "#263024",
        "border-chip": "#ECEBE6",
        "border-chip-dark": "#263024",
        // Brand
        "brand-green": "#0FB46B",
        "brand-green-start": "#1FD17C",
        "brand-green-mid": "#0FB388",
        "brand-green-end": "#0A9E5E",
        "brand-red": "#E8322A",
        "brand-red-start": "#FF6A5E",
        "brand-red-end": "#C0241D",
        // Premium accent — brushed gold for hairline highlights on dark/hero.
        "accent-gold": "#D9B25F",
        "accent-gold-soft": "#F0E0B8",
        "over-budget-red": "#E25555",
        "income-green": "#16A34A",
        // Category colors + soft backgrounds
        "cat-groceries": "#2FB872",
        "cat-groceries-soft": "#E6F6EE",
        "cat-dining": "#FF6B5E",
        "cat-dining-soft": "#FFEDEA",
        "cat-transport": "#2BB3FF",
        "cat-transport-soft": "#E6F4FF",
        "cat-shopping": "#7C5CFC",
        "cat-shopping-soft": "#EFEAFE",
        "cat-bills": "#F5A623",
        "cat-bills-soft": "#FEF2DE",
        "cat-entertainment": "#FF5CA8",
        "cat-entertainment-soft": "#FFEAF3",
        "cat-health": "#18BFA8",
        "cat-health-soft": "#E3F8F4",
        "cat-income": "#16A34A",
        "cat-income-soft": "#E6F6EC",
        "cat-education": "#3B82F6",
        "cat-education-soft": "#EFF6FF",
        "cat-travel": "#06B6D4",
        "cat-travel-soft": "#ECFEFF",
        "cat-fitness": "#10B981",
        "cat-fitness-soft": "#ECFDF5",
        // Tab accents
        "tab-home": "#0FB46B",
        "tab-activity": "#2BB3FF",
        "tab-budgets": "#7C5CFC",
        "tab-insights": "#F59E0B",
        "tab-settings": "#E8322A",
      },
    },
  },
  plugins: [],
}